---
title: "Class and Death: Workers Vs. Managers in Agriculture"
subtitle: "Exploration of Differences by Class in Agricultural Work"
author: "Luke Slipski"
date: "Published on `r format(Sys.time(), '%m-%d-%y')`"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 5
    page-layout: full
fig-cap-location: top
editor:
  markdown:
    wrap: 72
execute: 
  echo: false
  output: false
---


```{r}
library(tidyverse)
library(CAdeathserver)
library(merced.clc)
```


```{r}
df_cohort1 = read_rds(here::here("data/df_cohort1.rds")) %>% 
  mutate(month_of_death = as.integer(month.of.death),
         worker_manager = if_else(census_occ_code == "6050",
                                  "Worker",
                                  "Manager"),
         age_cat = case_when(recode_age_int < 40 ~ "1. <40",
                             recode_age_int >=40 & recode_age_int <=55 ~ "2. 40-55",
                             recode_age_int > 55 & recode_age_int <=64 ~ "3. 56-64",
                             recode_age_int > 64 ~ "4. 65+",
                             is.na(recode_age_int) ~ "5. Unknown",
                             TRUE ~ "ISSUE"))
```


```{r}
df_ipums = read_rds(here::here("data/demographics.rds")) %>% 
  # remove ipums labels which interact oddly with dt_table
  mutate(dplyr::across(.cols = dplyr::everything(),
                       .fns = unclass),
         sex = if_else(sex == 1 , "Male", "Female"),
         worker_manager = if_else(occ == 6050, "Worker", "Manager"),
         age_cat = case_when(age < 40 ~ "1. <40",
                             age >=40 & age <=55 ~ "2. 40-55",
                             age > 55 & age <=64 ~ "3. 56-64",
                             age > 64 ~ "4. 65+",
                             is.na(age) ~ "5. Unknown",
                             TRUE ~ "ISSUE"),
         hispanic = case_when(hispan == 0 ~ "Not Hispanic",
                            hispan == 1 ~ "Mexican",
                            hispan == 2 ~ "Puerto Rican",
                            hispan == 3 ~ "Cuban",
                            hispan == 4 ~ "Other",
                            hispan == 9 ~ "Not reported",
                            TRUE ~ "ISSUE"),
         race = case_when(hispan %in% c(1,2,3,4) ~ "Hispanic",
                          race == 1 ~ "White",
                          race == 2 ~ "Black",
                          race == 3 ~ "American Indian / Native American",
                          race %in% c(4,5,6) ~ "Asian / Pacific Islander",
                          TRUE ~ "Other"))
```

# Managers

## Race

### Age at Death

Reminder of how many deaths are in each race category
```{r}
df_cohort1 %>% 
  filter(worker_manager == "Manager") %>% 
  group_by(recode_race) %>% 
  summarize(number_deaths = n_distinct(id)) %>% 
  arrange(desc(number_deaths)) %>% 
  dt_table() %>% 
  add_commas("number_deaths")
```

Same as above but by year
```{r}
df_cohort1 %>% 
  filter(worker_manager == "Manager") %>% 
  group_by(year.of.death, recode_race) %>% 
  summarize(number_deaths = n_distinct(id),
            .groups = "drop") %>% 
  arrange(year.of.death, recode_race) %>% 
  dt_table() %>% 
  add_commas("number_deaths")
```




How many are missing an age value by race?
```{r}
df_cohort1 %>% 
  filter(worker_manager == "Manager" &
           is.na(recode_age_int)) %>% 
  count(recode_race) %>% 
  arrange(desc(n)) %>% 
  dt_table()
```

```{r}
df_cohort1 %>% 
  filter(worker_manager == "Manager") %>% 
  group_by(recode_race) %>% 
  summarize(mean_age_at_death = round(mean(recode_age_int, na.rm = T), 2)) %>% 
  arrange(desc(mean_age_at_death)) %>% 
  dt_table()
```

### Crude Death Rate, Overall, Excluding 2020

```{r}
numer_manager_race = df_cohort1 %>% 
  filter(worker_manager == "Manager" &
           year.of.death != 2020) %>% 
  group_by(recode_race) %>% 
  summarize(raw_death_count = n_distinct(id),
            .groups = "drop")

denom_manager_race = df_ipums %>% 
  filter(worker_manager == "Manager" &
           year != 2020) %>% 
  group_by(race) %>% 
  summarize(raw_people_count = sum(perwt),
            .groups = "drop")

crude_death_rate_race = numer_manager_race %>% 
  inner_join(denom_manager_race,
             by = c("recode_race" = "race")) %>% 
  mutate(crude_death_rate = round(raw_death_count / raw_people_count * 100000, 2))
```

### Crude Death Rate, By Year, Excluding 2020

```{r}
numer_manager_race_year = df_cohort1 %>% 
  filter(worker_manager == "Manager" &
           year.of.death != 2020) %>% 
  group_by(recode_race, 
           year.of.death) %>% 
  summarize(raw_death_count = n_distinct(id),
            .groups = "drop")

denom_manager_race_year = df_ipums %>% 
  filter(worker_manager == "Manager" &
           year != 2020) %>% 
  group_by(race, year) %>% 
  summarize(raw_people_count = sum(perwt),
            .groups = "drop")

crude_death_rate_race_year = numer_manager_race_year %>% 
  inner_join(denom_manager_race_year,
             by = c("recode_race" = "race",
                    "year.of.death" = "year")) %>% 
  mutate(crude_death_rate = round(raw_death_count / raw_people_count * 100000, 2))

crude_death_rate_race_year %>% 
  arrange(year.of.death, desc(crude_death_rate)) %>% 
  relocate(year.of.death) %>% 
  dt_table() %>% 
  add_commas("crude_death_rate")
```

```{r}
crude_death_rate_race_year %>% 
  ggplot() +
  geom_line(aes(x = year.of.death,
                y = crude_death_rate,
                colour = recode_race)) 
```


### Crude Death Rate, By Year, White Vs. Non-White

```{r}
numer_manager_race_year_white = df_cohort1 %>% 
  mutate(white_non_white = if_else(recode_race == "White", "White", "Non-White")) %>% 
  filter(worker_manager == "Manager") %>% 
  group_by(white_non_white, 
           year.of.death) %>% 
  summarize(raw_death_count = n_distinct(id),
            .groups = "drop")

denom_manager_race_year_white = df_ipums %>% 
  mutate(white_non_white = if_else(race == "White", "White", "Non-White")) %>% 
  filter(worker_manager == "Manager") %>% 
  group_by(white_non_white, year) %>% 
  summarize(raw_people_count = sum(perwt),
            .groups = "drop")

crude_death_rate_race_year_white = numer_manager_race_year_white %>% 
  inner_join(denom_manager_race_year_white,
             by = c("white_non_white" = "white_non_white",
                    "year.of.death" = "year")) %>% 
  mutate(crude_death_rate = round(raw_death_count / raw_people_count * 100000, 2))

crude_death_rate_race_year_white %>% 
  arrange(year.of.death, desc(crude_death_rate)) %>% 
  relocate(year.of.death) %>% 
  dt_table() %>% 
  add_commas("crude_death_rate")
```

```{r}
crude_death_rate_race_year_white %>% 
  ggplot() +
  geom_line(aes(x = year.of.death,
                y = crude_death_rate,
                colour = white_non_white)) +
  ggtitle("Manager Crude Death Rates: White vs. Non-White")
```

### Indirect Standardization White vs. Non-White

#### Age Categorical

Use white rates as references. 

```{r}
df_manager_deaths_age_whites = df_cohort1 %>% 
  mutate(white_non_white = if_else(recode_race == "White", "White", "Non-White")) %>% 
  filter(worker_manager == "Manager" &
           white_non_white == "White") %>% 
  group_by(year.of.death, 
           age_cat) %>% 
  summarize(raw_death_count = n_distinct(id),
            .groups = "drop")

df_manager_people_age_whites = df_ipums %>% 
  mutate(white_non_white = if_else(race == "White", "White", "Non-White")) %>% 
  filter(worker_manager == "Manager" &
           white_non_white == "White") %>% 
  group_by(year, 
           age_cat) %>% 
  summarize(raw_people_count = sum(perwt),
            .groups = "drop")

df_manager_rates_age_whites = df_manager_deaths_age_whites %>% 
  inner_join(df_manager_people_age_whites,
             by = c("year.of.death" = "year",
                    "age_cat" = "age_cat")) %>% 
  mutate(death_rate = raw_death_count / raw_people_count,
         death_rate_per_100k = raw_death_count / raw_people_count * 100000)

##########


df_manager_deaths_age_nonwhites = df_cohort1 %>% 
  mutate(white_non_white = if_else(recode_race == "White", "White", "Non-White")) %>% 
  filter(worker_manager == "Manager" &
           white_non_white == "Non-White") %>% 
  group_by(year.of.death, 
           age_cat) %>% 
  summarize(raw_death_count = n_distinct(id),
            .groups = "drop")

df_manager_people_age_nonwhites = df_ipums %>% 
  mutate(white_non_white = if_else(race == "White", "White", "Non-White")) %>% 
  filter(worker_manager == "Manager" &
           white_non_white == "Non-White") %>% 
  group_by(year, 
           age_cat) %>% 
  summarize(raw_people_count = sum(perwt),
            .groups = "drop") %>% 
  inner_join(df_manager_deaths_age_nonwhites,
             by = c("year" = "year.of.death",
                    "age_cat" = "age_cat")) %>% 
  inner_join(df_manager_rates_age_whites %>% 
               select(year.of.death,
                      age_cat,
                      death_rate),
             by = c("year" = "year.of.death",
                    "age_cat" = "age_cat")) %>% 
  mutate(nonwhite_expected_death_count = death_rate * raw_people_count,
         adjusted_death_rate = raw_death_count / nonwhite_expected_death_count)

df_manager_std_mortality_rate_age_nonwhites = df_manager_people_age_nonwhites %>% 
  group_by(year) %>% 
  summarize(expected_deaths = round(sum(nonwhite_expected_death_count),2),
            actual_deaths = round(sum(raw_death_count), 2)) %>% 
  mutate(std_mortality_ratio = round(actual_deaths / expected_deaths, 2))

df_manager_std_mortality_rate_age_nonwhites %>% 
  dt_table()
```











